CREATE TABLE GUESTBOOK (
    IDX NUMBER PRIMARY KEY,
    NAME VARCHAR2(30),
    SUBJECT VARCHAR(100),
    CONTENT VARCHAR2(1000),
    EMAIL VARCHAR(100),
    PWD VARCHAR(30),
    REGDATE DATE DEFAULT SYSDATE
);

CREATE SEQUENCE GUESTBOOK_SEQ NOCACHE;

INSERT INTO GUSETBOOK
    (IDX, NAME, SUBJECT, CONTENT, EMAIL, PWD, REGDATE)
    VALUES(GUESTBOOK_SEQ.NEXTVAL, '홍길동', '제목1', '내용1', 'hong@test.com', '1111', SYSDATE-3);
    
INSERT INTO GUSETBOOK
(IDX, NAME, SUBJECT, CONTENT, EMAIL, PWD, REGDATE)
VALUES(GUESTBOOK_SEQ.NEXTVAL, '홍이동', '제목2', '내용2', 'hongtwo@test.com', '2222', SYSDATE-2);

INSERT INTO GUSETBOOK
(IDX, NAME, SUBJECT, CONTENT, EMAIL, PWD, REGDATE)
VALUES(GUESTBOOK_SEQ.NEXTVAL, '홍삼동', '제목3', '내용3', 'hongthree@test.com', '3333', SYSDATE-1);

commit;

SELECT * FROM GUSETBOOK ORDER BY IDX;