-- (SYSTEM)
/*
    ■ DB생성(유저) - DB명(유저명) : TEST
                  - 암호 : testpw
    ■ 역할(롤) 설정 : CONNECT, RESOURCE
    ■ 권한 추가 : VIEW 생성 권한
*/

-- USER SQL
ALTER USER "TEST" IDENTIFIED BY "testpw" 
DEFAULT TABLESPACE "SYSTEM"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK ;

-- ROLES
ALTER USER "TEST" DEFAULT ROLE "CONNECT","RESOURCE";

-- SYSTEM PRIVILEGES
GRANT CREATE ANY VIEW TO "TEST" ;

/*■ 테이블 생성*/
-- MEMBER Table Create SQL
CREATE TABLE MEMBER
(
    ID          VARCHAR2(20)    NOT NULL, 
    NAME        VARCHAR2(30)    NOT NULL, 
    PASSWORD    VARCHAR2(20)    NOT NULL, 
    PHONE       VARCHAR2(20)    NULL, 
    EMAIL       VARCHAR2(50)    NULL, 
    CONSTRAINT MEMBER_PK PRIMARY KEY (ID)
);



-- MEMBER Table Create SQL
CREATE TABLE BOARD
(
    BNO        NUMBER            NOT NULL, 
    TITLE      VARCHAR2(150)     NOT NULL, 
    CONTENT    VARCHAR2(3000)    NOT NULL, 
    ID         VARCHAR2(20)      NOT NULL, 
    REGDATE    DATE    DEFAULT SYSDATE  NOT NULL, 
    CONSTRAINT BOARD_PK PRIMARY KEY (BNO)
);


ALTER TABLE BOARD
    ADD CONSTRAINT FK_BOARD_ID_MEMBER_ID FOREIGN KEY (ID)
        REFERENCES MEMBER (ID);

/*
인덱스 생성 : BOARD 테이블 ID 컬럼에 인덱스 생성
- 인덱스명: BOARD_IDX_ID
*/
-- (TEST)
CREATE INDEX BOARD_IDX_ID ON BOARD(ID);

