/*
    시퀀스(SEQUENCE) : DB에서 제공하는 자동채번 객체
    생성 : CREATE SEQUENCE 시퀀스명;
    
    시퀀스명.NEXTVAL : 시퀀스 번호(값) 생성
    시퀀스명.CURRVAL : 
    
*/

   CREATE SEQUENCE  SEQUENCE1  
   MINVALUE 1 MAXVALUE 99999999999999999999999
   INCREMENT BY 1
   START WITH 1
   CACHE 20 NOORDER  NOCYCLE ;

SELECT SEQUENCE1.NEXTVAL FROM DUAL; -- 계속 실행되면 값이 1씩(INCREMENT BY 1) 증가함
-----------------
SELECT * FROM BOOK;
SELECT MAX(BOOKID), MAX(BOOKID) + 1 FROM BOOK;
SELECT MAX(AAA), NVL(MAX(AAA), 0) + 1 FROM AAA; -- 데이터가 없을 때(NULL)
------
-- BOOK 테이블에 INSERT 작업, BOOKID 최대값 + 1
INSERT INTO book
    (BOOKID, BOOKNAME, PUBLISHER, PRICE)
VALUES ((SELECT NVL(MAX(BOOKID), 0) + 1 FROM BOOK), 'MAX(BOOKID) + 1', 'ITBOOK', 20000);

COMMIT;

SELECT * FROM BOOK ORDER BY BOOKID DESC;
---------------------
-- 시퀀스 사용(시작번호 50, NOCACHE)
CREATE SEQUENCE SEQ_BOOK
START WITH 50
INCREMENT BY 1 -- 생략시 동일 (디폴트값이 1씩 증가하는 것으로 되어있음)
NOCACHE; -- 캐시사용 안함

SELECT SEQ_BOOK.NEXTVAL FROM DUAL;
------ BOOK 테이블에 시퀀스 사용
INSERT INTO BOOK
    (BOOKID, BOOKNAME, PUBLISHER, PRICE)
VALUES(SEQ_BOOK.NEXTVAL,
        'SEQ_BOOK.NEXTVAL 적용', 'ITBOOK', 20000);
        
COMMIT;

SELECT * FROM BOOK ORDER BY BOOKID DESC;

--------------------시퀀스 삭제
drop sequence SEQUENCE1;
